export const commonMedicines = [
  "Abel Moschus",
  "Abies Canadensis",
  "Abies Nigra",
  "Abroma Augusta",
  "Abroma Radix",
  "Abrotanum",
  "Abrus Precatorius",
  "Absinthium",
  "Acalypha Indica",
  "Acer Negundo",
  "Acetanilidum",
  "Achyranthes Aspera",
  "Acidum Aceticum",
  "Acidum Acetylsalicylicum",
  "Acidum Ascorbicum",
  "Acidum Benzoicum",
  "Acidum Boracicum",
  "Acidum Butyricum",
  "Acidum Carbolicum",
  "Acidum Carbonicum",
  "Acidum Chromicum",
  "Acidum Chrysophanicum",
  "Acidum Citricum",
  "Acidum Formicum",
  "Acidum Gallicum",
  "Acidum Hippuricum",
  "Acidum Hydrcyanicum",
  "Acidum Hydrofluoricum",
  "Acidum Lacticum",
  "Acidum Mauriaticum",
  "Acidum Nitricum",
  "Acidum Nitromuriaticum",
  "Acidum Oxalicum",
  "Acidum Phosphoricum",
  "Acidum Picricum",
  "Acidum Salicylicum",
  "Acidum Sarcolacticum",
  "Acidum Sulphuricum",
  "Acidum Sulphurosum",
  "Acidum Tannicum",
  "Acidum Tartaricum",
  "Acidum Uricum",
  "Aconitum Ferox",
  "Aconitum Napellus",
  "Aconitum Radice",
  "Acorus Calamus",
  "Actaea Spicata",
  "Adonis Vernalis",
  "Adrenalium",
  "Adrenocorticotrophin",
  "Aegle Folia",
  "Aegle Marmelos",
  "Aesculus Hippocastanum",
  "Aether Aethylicus",
  "Aethiops Antimonialis",
  "Aethiops Merucurialis Mineralis",
  "Aethusa Cynapium",
  "Agaricus Muscarius",
  "Agave Americana",
  "Agnus Castus",
  "Agraphis Nutans",
  "Ailanthus Glandulosus",
  "Aletris Farinosa",
  "Alfalfa",
  "Allium Cepa",
  "Allium Sativum",
  "Allium Ursinum",
  "Alloxanum",
  "Alnus Glutinosa",
  "Aloe Socotrina",
  "Alstonia Constricta",
  "Alstonia Scholaris",
  "Althea Officinalis",
  "Alumen",
  "Alumina",
  "Aluminium Metallicum",
  "Aluminium Phosphoricum",
  "Aluminium Sulphuricum",
  "Ambra Grisea",
  "Ambrosia Artemisiaefolia",
  "Ammi Visnaga",
  "Ammoniacum Gummi",
  "Ammonium Aceticum",
  "Ammonium Benzoicum",
  "Ammonium Bromidum",
  "Ammonium Carbonicum",
  "Ammonium Causticum",
  "Ammonium Iodatum",
  "Ammonium Muriaticum",
  "Ammonium Nitricum",
  "Ammonium Phosphoricum",
  "Ammonium Picricum",
  "Ammonium Valerianicum",
  "Amoora Rohituka",
  "Amygdalus Amara",
  "Amygdalus Persica",
  "Amyl Nitrosum",
  "Anacardium Occidentale",
  "Anacardium Orientale",
  "Anagallis Arvensis",
  "Ananassa",
  "Anatherum Muricatum",
  "Andrographis Paniculata",
  "Anethum Graveolens",
  "Angelica Archangelica",
  "Angustura Vera",
  "Anilinum",
  "Anilinum Sulphuricum",
  "Anthemis Nobilis",
  "Anthracinum",
  "Anthrakokali",
  "Antimonium Arsenicicum",
  "Antimonium Arsenicosum",
  "Antimonium Crudum",
  "Antimonium Iodatum",
  "Antimonium Muriaticum",
  "Antimonium Oxydatum",
  "Antimonium Sulphuratum Aureum",
  "Antimonium Tartaricum",
  "Antipyrinum",
  "Apis Mellifica",
  "Apis Virus",
  "Apium Graveolens",
  "Apocynum Androsaemifolium",
  "Apocynum Cannabinum",
  "Apomorphia",
  "Apomorphinum Muriaticum",
  "Aqua Marina",
  "Aquilegaia Vulgaris",
  "Aralia Racemosa",
  "Aranea Diadema",
  "Areca Catechu",
  "Argemone Mexicana",
  "Argentum Cyanatum",
  "Argentum Iodatum",
  "Argentum Metallicum",
  "Argentum Muriaticum",
  "Argentum Nitricum",
  "Argentum Oxydatum",
  "Argentum Phosphoricum",
  "Aristolochia Clematis",
  "Aristrolochia Serpentaria",
  "Arnica Montana",
  "Arnica Montana Radix",
  "Arsenicum Album",
  "Arsenicum Hydrogeniatum",
  "Arsenicum Iodatam",
  "Arsenicum Metallicum",
  "Arsenicum Sulph.Falvum",
  "Arsenicum Sulphuratum Rubrum",
  "Artemisia Vulgaris",
  "Arum Maculatum",
  "Arum Triphyllum",
  "Arundo Mauritanica",
  "Asafoetida",
  "Asarum Europaeum",
  "Ascaris Lumbricoides",
  "Asclepias Syriaca",
  "Asclepias Tuberosa",
  "Aspidosperma Quebracho",
  "Astacus Fluviatilis",
  "Asterias Rubens",
  "Atista Indica",
  "Atista Radix",
  "Atropinum",
  "Atropinum Sulphuricum",
  "Auromycine",
  "Aurum Iodatum",
  "Aurum Metallicum",
  "Aurum Muriaticum",
  "Aurum Muriaticum Natronatum",
  "Aurum Sulphuratum",
  "Avena Sativa",
  "Aviaire",
  "Azadirachta Indica",
  "BACILLUS NO-10",
  "BACILLUS NO-7",
  "BALSAMODENDRON M (GUGGULU)",
  "Bacillinum",
  "Bacopa Munnieri (Brahmi)",
  "Badiaga",
  "Balsum Peruvianum",
  "Baptisia Tinctoria",
  "Barosma Crenata",
  "Bartya Iodata",
  "Bartya Muriatica",
  "Bartya Sulphurata",
  "Baryta Acetica",
  "Baryta Carbonica",
  "Belladonna",
  "Bellis Perennis",
  "Benzenum",
  "Benzinum Nitricum",
  "Benzocainum",
  "Benzoinum",
  "Berberies Aquifolium",
  "Berberis Vulgaris",
  "Beryllium Metallicum",
  "Beta Vulgaris",
  "Bismuthum Metallicum",
  "Bismuthum Oxydatum",
  "Bismuthum Sub-Nitricum",
  "Blatta Orientalis",
  "Boerhaavia  Diffusa",
  "Boldo",
  "Borax",
  "Bothrops Lanceolatus",
  "Bovista",
  "Bromium",
  "Brucinum",
  "Bryonia Alba",
  "Bryophyllum Calycinum",
  "Bufo Rana",
  "CARCINO ADENO STOMACH",
  "CARCINO SC MAMMAE",
  "CARCINOMA ADENO PAP COLON",
  "CARCINOSIN SQUAM. PULM",
  "CARDIOSPERMUM HELICACABUM",
  "CHLORPROMAZINE",
  "CYDONIA VULGARIS",
  "Cactus Gandiflorus",
  "Cadmium Arsencicum",
  "Cadmium Arsenicosum",
  "Cadmium Fluoratum",
  "Cadmium Iodatum",
  "Cadmium Metallicum",
  "Cadmium Phosphoricum",
  "Cadmium Sulphuratum",
  "Cadmium Suphuricum",
  "Caesalpinia Bounducella",
  "Caffeinum",
  "Cajuputum",
  "Caladium Seguinum",
  "Calcarea  Arsenicica",
  "Calcarea Acetica",
  "Calcarea Arsenicosa",
  "Calcarea Bromata",
  "Calcarea Carbonica",
  "Calcarea Caustica",
  "Calcarea Fluorica",
  "Calcarea Hypophosphorosa",
  "Calcarea Iodata",
  "Calcarea Muriatica",
  "Calcarea Ova Tosta",
  "Calcarea Oxalica",
  "Calcarea Phosphorica",
  "Calcarea Picrata",
  "Calcarea Silicata",
  "Calcarea Sulphurica",
  "Calculi Biliarii",
  "Calendula Officinalis",
  "Calotropis Gigantea",
  "Caltha Paustris",
  "Camphora",
  "Camphora Monobromata",
  "Cannabis Indica",
  "Cannabis Sativa",
  "Cantharis",
  "Capsicum Annum",
  "Carbo Animalis",
  "Carbo Vegetabilis",
  "Carboneum Oxygenisatum",
  "Carboneum Sulphuratum",
  "Carcinosin",
  "Carcinosin Mix",
  "Carduus Benedictus",
  "Carduus Marianus",
  "Carica Papaya",
  "Carlsbad",
  "Carum Carvi",
  "Cascara Sagrada",
  "Cascarilla",
  "Cassia Fistula",
  "Cassia Sophera",
  "Castanea Vesca",
  "Castor Equi",
  "Castoreum",
  "Caulophyllum Thalictroides",
  "Causticum",
  "Ceanothus Americanus",
  "Cedron",
  "Cenchris Contortrix",
  "Cephalandra Indica",
  "Cereus Bonplandii",
  "Cerium Metallicum",
  "Cerium Oxalicum",
  "Chamomilla",
  "Chaparo Amargoso",
  "Chaulmoograe",
  "Chelidonium Majus",
  "Chelone Glabra",
  "Chenopodium Anthelminticum",
  "Cherianthus Cheri",
  "Chimaphila Umbellata",
  "Chininum Arsenicicum",
  "Chininum Arsenicosum",
  "Chininum Bromhydricum",
  "Chininum Muriaticum",
  "Chininum Purum",
  "Chininum Sulphuricum",
  "Chionanthus Virginica",
  "Chlolarum",
  "Chloralum",
  "Chlorinum",
  "Chloroformum",
  "Chocolate",
  "Cholesterinum",
  "Chrysarobinum",
  "Cicuta Maculata",
  "Cicuta Virosa",
  "Cimex Lectularius",
  "Cimicifuga Racemosa",
  "Cina",
  "Cinchona Officinalis",
  "Cinchoninum Sulphuricum",
  "Cineraria Maritima",
  "Cinnabaris",
  "Cinnamomum",
  "Cistus Canadensis",
  "Citrus Limonum",
  "Citrus Vulgaris",
  "Clematis Erecta",
  "Clerodendron Infortunatum",
  "Cobaltum Metallicum",
  "Cobaltum Nitricum",
  "Coca",
  "Cocainum Muriaticum",
  "Cocculus Indicus",
  "Coccus Cacti",
  "Coclearia Armoracia",
  "Codeinum",
  "Coffea Cruda",
  "Coffea Tosta",
  "Cola Acuminata",
  "Colchicinum",
  "Colchicum Autumnale",
  "Collinsonia Canadensis",
  "Colocynthis",
  "Condurango",
  "Conium Maculatum",
  "Convallaria Majalis",
  "Copaiva Officinalis",
  "Corallium Rubrum",
  "Coriandrum Sativum",
  "Cornus Circinata",
  "Cortisone",
  "Cotyledon Umbilicus",
  "Crataegus Oxyacantha",
  "Crocus Sativus",
  "Crotalus Cascavella",
  "Crotalus Horridus",
  "Croton Tiglium",
  "Crysanthemum parthenium",
  "Cubeba Officinalis",
  "Cucurbita Pepo",
  "Culex Pipiens",
  "Cupressus Lawsoniana",
  "Cuprum Aceticum",
  "Cuprum Arsenicosum",
  "Cuprum Carbonicum",
  "Cuprum Metallicum",
  "Cuprum Nitricum",
  "Cuprum Sulphuratum",
  "Cuprum Sulphuricum",
  "Curare",
  "Curcuma Longa",
  "Cyclamen Europaeum",
  "Cyclohexane",
  "Cynodon Dactylon",
  "Cypripedium Pubescens",
  "D.N.A",
  "DYSENTRY-CO",
  "Damiana",
  "Daphane Indica",
  "Desmodium Gangeticum",
  "Digitalinum",
  "Digitalis Purpurea",
  "Dioscorea Vilosa",
  "Diphtherinum",
  "Dolichos",
  "Drosera Rotundifolia",
  "Dulcamara",
  "ECLIPTA ALBA (BHRINGRAJ)",
  "Echinacea Angustifolia",
  "Elaps Corallinus",
  "Elaterium",
  "Electricitas",
  "Embelia Ribes",
  "Embelica Officinalis",
  "Emetinum Muriaticum",
  "Ephedra Vulgaris",
  "Ephedrinum",
  "Epigaea Repens",
  "Epiphegus Virginiana",
  "Equisetum Hyemale",
  "Erigeron Canadense",
  "Eriodictyon Glutinosum",
  "Eryngium Aquaticum",
  "Eschscholtzia Californica",
  "Eserinum",
  "Eucalyptus Globulus",
  "Euonymus Atropurpurea",
  "Euonymus Europaeus",
  "Eupatorium Perfoliatum",
  "Eupatorium Purpureum",
  "Euphorbia Corollata",
  "Euphorbinum",
  "Euphrasia Officinalis",
  "Eupion",
  "FOENUGREEK (TRIGONELLA FOENUM)",
  "Fagopyrum Esculentum",
  "Feltauri",
  "Ferrum Aceticum",
  "Ferrum Arsenicicum",
  "Ferrum Arsenicosum",
  "Ferrum Bromatum",
  "Ferrum Carbonicum",
  "Ferrum Iodatum",
  "Ferrum Magneticum",
  "Ferrum Metallicum",
  "Ferrum Muriaticum",
  "Ferrum Oxydatum",
  "Ferrum Phosphoricum",
  "Ferrum Picricum",
  "Ferrum Sulphuricum",
  "Ficus Indica",
  "Ficus Religiosa",
  "Filaria Loa-Loa",
  "Filix Mas",
  "Foeniculum Vulgare",
  "Folliculinum",
  "Fornica Rufa",
  "Fragaria Vesca",
  "Fraxinus Americana",
  "Fucus Vesiculosus",
  "Galega Officinalis",
  "Gambogia",
  "Gaultheria Procumbens",
  "Gelsemiun Sempervirens",
  "Gentiana Cruciata",
  "Gentiana Lutea",
  "Geranium Maculatum",
  "Ginkgo Biloba",
  "Ginseng",
  "Glononium",
  "Glycerinum",
  "Glycyrrhiza Glabra",
  "Gnaphalium Uliginosum",
  "Gnaphalium polycephalum",
  "Gossypium Herbaceum",
  "Granatum",
  "Graphites",
  "Gratiola Officinalis",
  "Grindelia Robusta",
  "Guaco",
  "Guaiacum",
  "Guarana",
  "Guarea Trichilodies",
  "Gun Powder",
  "Gymnema Sylvestre",
  "Gymnocladus Canadensis",
  "Haematoxylon Campachianum",
  "Hamamelis Virginica",
  "Hecla Lava",
  "Hedera Helix",
  "Helianthus Annuus",
  "Heliotropium Peruvianum",
  "Helleborus Niger",
  "Heloderma",
  "Helonias Dioica",
  "Hemidesmus Indica",
  "Hepar Sulphur",
  "Hippomane Mancinella",
  "Histaminum",
  "Hoang-Nan",
  "Holarrhena Antidysenterica",
  "Homarus Gammerus",
  "Hura Brasiliensis",
  "Hydrangea Arborescens",
  "Hydrastinum",
  "Hydrastis Canadensis",
  "Hydrocortisone",
  "Hydrocotyle Asiatica",
  "Hydrogen",
  "Hydrophobinum",
  "Hygrophilla Spinosa",
  "Hyoscyamus Niger",
  "Hypericum Perforatum",
  "Hypophysine",
  "Hypophysine La",
  "Iberis Amara",
  "Ignatia Amara",
  "Ilex Aquifolium",
  "Illicium Anisatum",
  "Indigo",
  "Indium Metallicum",
  "Influenzinum",
  "Ingluvin",
  "Insulinum",
  "Iodium",
  "Iodoformium",
  "Ipecacuanha",
  "Iridium Metallicum",
  "Iris Tenax",
  "Iris Versicolor",
  "Jaborandi",
  "Jacaranda Caroba",
  "Jalapa",
  "Janosia Ashoka",
  "Jatropha Curcas",
  "Juglans Cinerea",
  "Juglans Regia",
  "Juncus Effusus",
  "Juniperus Communis",
  "Juniperus Virginiana",
  "Justicia Adhatoda",
  "Kali Aceticum",
  "Kali Arsenicosum",
  "Kali Bicarbonicum",
  "Kali Bichromicum",
  "Kali Bromatum",
  "Kali Carbonicum",
  "Kali Causticum",
  "Kali Chloricum",
  "Kali Chromicum",
  "Kali Cyanatum",
  "Kali Ferrocyanatum",
  "Kali Hypophosphoricum",
  "Kali Iodatum",
  "Kali Muriaticum",
  "Kali Nitricum",
  "Kali Permanganicum",
  "Kali Phosphoricum",
  "Kali Picricum",
  "Kali Sulphuricum",
  "Kali oxalicum",
  "Kalmia Latifolia",
  "Kaolinum",
  "Kino De Malabar",
  "Kreosotum",
  "Lac Caninum",
  "Lac Defloratum",
  "Lac Felinum",
  "Lac Vaccinum",
  "Lachesis",
  "Lachnanthes Tinctoria",
  "Lactuca Virosa",
  "Lamium Album",
  "Lapis Albus",
  "Lappa Major",
  "Lathyrus Sativus",
  "Latrodectus Mactans",
  "Laurocerasus",
  "Lecithinum",
  "Ledum Plasture",
  "Lemna Minor",
  "Leonuorus Cardica",
  "Leptandra",
  "Leucas Aspera",
  "Liatris Spicata",
  "Lilium Tigrinum",
  "Lithium Benzoicum",
  "Lithium Bromatum",
  "Lithium Carbonicum",
  "Lobelia Inflata",
  "Lolium Temulentum",
  "Luesinum",
  "Luffa Amara",
  "Luffa Operculata",
  "Lupulus",
  "Luteinum",
  "Lycopersicum Esculentum",
  "Lycopodium Clavatum",
  "Lycopus Virginicus",
  "MOMORDICA CHARANTIA",
  "MORGAN GAERTNER",
  "MORINGA OLEIFERA",
  "MUSA SAPIENTUM",
  "MUTABILLIS",
  "Magnesia Carbonica",
  "Magnesia Muriatica",
  "Magnesia Oxydata",
  "Magnesia Phosphoricum",
  "Magnesia Sulphurica",
  "Magnetis Polus Australis",
  "Magnolia Grandiflora",
  "Malandrinum",
  "Malaria Officinalis",
  "Manganum Aceticum",
  "Manganum Carbonicum",
  "Manganum Metallicum",
  "Manganum Muriaticum",
  "Manganum Oxydatum Nigrum",
  "Mangifera Indica",
  "Medorrhinum",
  "Medusa",
  "Melcum Sale",
  "Melilotus Alba",
  "Melilotus Officinalis",
  "Mentha Piperita",
  "Mentholum",
  "Menyanthes Trifoliata",
  "Mephitis Mephitica",
  "Mercurialis Perennis",
  "Mercurius Aceticus",
  "Mercurius Corrosivus",
  "Mercurius Cyanatus",
  "Mercurius Dulcis",
  "Mercurius Et Kali Iodatus",
  "Mercurius Iod.Flavus",
  "Mercurius Iod.Ruber",
  "Mercurius Nitricus",
  "Mercurius Oxydatus Flavus",
  "Mercurius Percipitatus Albus",
  "Mercurius Percipitatus Ruber",
  "Mercurius Solubilis",
  "Mercurius Sulphuricus",
  "Mercurius Vivus",
  "Mezereum",
  "Mica",
  "Millefolium",
  "Mitchella Repens",
  "Morbillinum",
  "Morphinum",
  "Morphinum Aceticum",
  "Morphinum Muriaticum",
  "Moschus",
  "Mullein Flower",
  "Murex Purpurea",
  "Mygale",
  "Myosotis Arvensis",
  "Myrica Cerifera",
  "Myristica Sebifera",
  "Myrtus Communis",
  "NIGELLA SATIVA (B CARAWAY)",
  "Naja Tripudians",
  "Naphthalinum",
  "Narcissus Pseudonaricissus",
  "Narcotinum",
  "Natrum Aceticum",
  "Natrum Arsenicosum",
  "Natrum Arsenicum",
  "Natrum Bormatum",
  "Natrum Cacodylicum",
  "Natrum Carbonicum",
  "Natrum Causticum",
  "Natrum Chloricum",
  "Natrum Fluoricum",
  "Natrum Hypochlorosum",
  "Natrum Hypophosphorosum",
  "Natrum Iodatum",
  "Natrum Muriaticum",
  "Natrum Nitricum",
  "Natrum Phosphoricum",
  "Natrum Salicylicum",
  "Natrum Sulphuricum",
  "Natrum Sulphurosum",
  "Niccolum Carbonicum",
  "Niccolum Metallicum",
  "Niccolum Sulphuricum",
  "Nicotinum",
  "Nitri Spiritus Dulcis",
  "Nuphar Lutea",
  "Nux Moschata",
  "Nux Vomica",
  "Nyctanthes Arbortristis",
  "Nymphaea Odorata",
  "Ocimum Basilicum",
  "Ocimum Canum",
  "Ocimum Sanctum",
  "Oenanthe Crocata",
  "Oleander",
  "Oleum Animale",
  "Oleum Morrhuae",
  "Oleum Ricini",
  "Oleum Santali",
  "Onosmodium Virginianum",
  "Opium",
  "Opuntia Vulgaris",
  "Orchitinum",
  "Origanum Majorana",
  "Origanum Vulgare",
  "Ornithogalum Umbellatum",
  "Osmium Metallicum",
  "Osteo Arthritic Nosode",
  "Ovarinum",
  "Oxydendrum Arboreum",
  "Oxytropis Campestris",
  "Oxyurus Vermicularis",
  "Ozone",
  "PHYLLANTHUS N (BHOOMI AMLA)",
  "PROTEUS MORGANI",
  "Paeonia Officinalis",
  "Palladium",
  "Pancreatinum",
  "Paraffinum",
  "Parathyroidinum",
  "Paratyphoidinum B",
  "Pareira Brava",
  "Paris Quadrifolia",
  "Parotidinum",
  "Passiflora Incarnata",
  "Penicillinum",
  "Penthorum Sedodies",
  "Pepsinum",
  "Persicaria Acris",
  "Pertussinum",
  "Pestinum",
  "Petroleum",
  "Petroselinum Sativum",
  "Phaseolus Nanus",
  "Phaseolus Vulgaris",
  "Phellandrinum Aquaticum",
  "Phenolphthaleinum",
  "Phosphorus",
  "Phosphorus Rubrum",
  "Physalis Alkekengi",
  "Physostigma Venenosum",
  "Phytolacca",
  "Phytolacca Berry",
  "Picrotoxinum",
  "Pilocarpinum Muriaticum",
  "Pilocarpinum Nitricum",
  "Pimpinella Saxifraga",
  "Pinus Lambertiana",
  "Pinus Sylvestris",
  "Piper Methysticum",
  "Piper Nigrum",
  "Piscidia Erythrina",
  "Pituitrine",
  "Pix Liquida",
  "Placenta",
  "Plantago Major",
  "Plantanus Occidentalis",
  "Platinum Metallicum",
  "Platinum Muriaticum",
  "Plumbago Littoralis",
  "Plumbum Aceticum",
  "Plumbum Carbonicum",
  "Plumbum Chromicum",
  "Plumbum Iodatum",
  "Plumbum Metallicum",
  "Podophyllin",
  "Podophyllum Peltatum",
  "Pollantinum",
  "Polygonum Punctatum",
  "Polygonum Sagittatum",
  "Populus Candicans",
  "Pothos Foetidus",
  "Prednisone",
  "Prostatinum",
  "Prunus Spinosa",
  "Prunus Virginiana",
  "Psoralea Corylifolia",
  "Psorinum",
  "Ptelea Trifolia",
  "Pulsatilla Nigricans",
  "Pyrogenium",
  "Quassia Amara",
  "Quillaya Saponaria",
  "R.N.A",
  "Radium Bromatum",
  "Ranunculus Bulbosus",
  "Ranunculus Sceleratus",
  "Raphanus Sativus",
  "Ratanhia",
  "Rauvolfia Serpentina",
  "Renalis Calculi",
  "Renine",
  "Resorcinum",
  "Rhamnus Californica",
  "Rhamnus Catharticus",
  "Rhamnus Frangula",
  "Rheum",
  "Rhododendron Chrysanthum",
  "Rhus Aromatica",
  "Rhus Glabra",
  "Rhus Toxicodendron",
  "Rhus Venenata",
  "Ricinus Communis",
  "Robinia Pseudacacia",
  "Rosa Damascena",
  "Rosmarinus Officinalis",
  "Rubia Tinctor",
  "Rumex Acetosa",
  "Rumex Crispus",
  "Ruta Graveolens",
  "SALMONELLA ENTERIDITIS",
  "SIMAROUBA GLAUCA(SIMARUBA AMARA)",
  "SYCOTI-CO",
  "Sabadilla",
  "Sabal Serrulata",
  "Sabina",
  "Saccharum Lactis",
  "Saccharum Offinale",
  "Saliva Officinalis",
  "Salix Nigra",
  "Salol",
  "Samarium Oxydatum",
  "Sambucus Canadensis",
  "Sambucus Nigra",
  "Sanguinaria Canadensis",
  "Sanguinarina Nitrica",
  "Sanguinarinum",
  "Sanguisuga Officinalis",
  "Sanicula Europaea",
  "Santoninum",
  "Sarracenia Purpurea",
  "Sarsaparilla",
  "Scopolaminum",
  "Scorpion",
  "Scrophularia Nodosa",
  "Scutellaria",
  "Secale Cornutum",
  "Sedum Acre",
  "Selenium",
  "Sempervivum Tectorum",
  "Senecio Aurantiacus",
  "Senecio Aureus",
  "Senega",
  "Senna",
  "Sepia",
  "Serum Anguillae",
  "Silica Marina",
  "Silicea",
  "Sinapis Alba",
  "Sinapis Nigra",
  "Sol",
  "Solanum Nigrum",
  "Solanum Xanthocarpus",
  "Solidago Virgaurea",
  "Sparteinum Sulphuricum",
  "Spigelia",
  "Spigelia Marylandica",
  "Spiranthes Autumnalis",
  "Spiritus Quercus Glandium",
  "Spongia Tosta",
  "Squilla",
  "Stannum Iodatum",
  "Stannum Metallicum",
  "Staphylococcinum",
  "Staphysagria",
  "Stellaria Media",
  "Sticta Pulmonaria",
  "Stigmata Maydis",
  "Stilboestrolum",
  "Stillngia Sylvatica",
  "Stramonium",
  "Strepto Coccinum",
  "Streptomycinum",
  "Strontium Carbonicum",
  "Strontium Hydroxide",
  "Strophanthus Hispidus",
  "Strychninum",
  "Strychninum Arsenicicum",
  "Strychninum Nitricum",
  "Strychninum Phosphoricum",
  "Strychninum Valerianicum",
  "Sulfonamide",
  "Sulphanilamidum",
  "Sulphur",
  "Sulphur Iodatum",
  "Sumbul",
  "Swertia Chirata",
  "Symphoricarpus Racemosus",
  "Symphytum Officinale",
  "Syphilinum",
  "Syzygium Jambolanum",
  "Tabacum",
  "Tamus Communis",
  "Tanacetum Vulgare",
  "Taraxacum",
  "Tarentula Cubensis",
  "Tarentula Hispanica",
  "Taxus Baccata",
  "Tellurium",
  "Terebinthlnae Oleum",
  "Terminalia Arjuna",
  "Terminalia Chebula",
  "Terpinum",
  "Teucrium Marum Verum",
  "Thallium Metallicum",
  "Thalllium Arsenicicum",
  "Thaspium Aureum",
  "Thea Chinensis",
  "Theridion",
  "Thiosinaminum",
  "Thlaspi Bursa Pastoris",
  "Thuja Occidentalis",
  "Thymol",
  "Thymus Vulgaris",
  "Thymusine",
  "Thyroidinum",
  "Thyroxinum",
  "Tilia Europaea",
  "Tinospora Cordifolia",
  "Titanium",
  "Tnt",
  "Tribulus Terrestris",
  "Trichosanthes Dioica",
  "Trifolium Pratense",
  "Trifolium Repens",
  "Trillium",
  "Triticum Repens",
  "Trombidium",
  "Tuberculinum",
  "Tussilago Farfara",
  "Tylophora Indica",
  "Typhoidinum",
  "Uranium Muriaticum",
  "Uranium Nitricum",
  "Urea",
  "Urtica Urens",
  "Usnea Barbata",
  "Ustilago Maydis",
  "Uva Ursi",
  "VITIS VINIFERA",
  "Vaccinium Myrtillus",
  "Vaccinotoxinum",
  "Vanadium Metallicum",
  "Variolinum",
  "Veleriana Officinalis",
  "Veratrum Album",
  "Veratrum Viride",
  "Verbascum Thapsus",
  "Verbena Officinalis",
  "Vernonia Anthelmintica",
  "Vespa Crabro",
  "Viburnum Opulus",
  "Viburnum Prunifolium",
  "Vinca Major",
  "Vinca Minor",
  "Vincetoxicum Officinalis",
  "Viola Odorata",
  "Viola Tricolor",
  "Vipera Torva",
  "Viscum Album",
  "Wiesbaden",
  "Withania Somnifera",
  "Wyethia Heleniodes",
  "X Rays",
  "Xanthoxylum Fraxineum",
  "Xerophyllum Asphodelodies",
  "Yohimbinum",
  "Yucca Filamentosa",
  "Zincum Aceticum",
  "Zincum Bromatum",
  "Zincum Carbonicum",
  "Zincum Cyanatum",
  "Zincum Iodatum",
  "Zincum Metallicum",
  "Zincum Muriaticum",
  "Zincum Oxydatum",
  "Zincum Phosphoratum",
  "Zincum Sulphuricum",
  "Zincum Valerianicum",
  "Zingiber"
];